Repository mariozaizar/language-eml, pull requests merged in 2019-06, with the labels that each got.

#23 IPv6 matching fix
  .npmignore
  .ruby-version
  LICENSE.md
  grammars/language-eml.cson
Labels: Bug, Maintenance

#20 Fix package repo url
  package.json
Labels: :heart: Community, Maintenance

#25 Fixes #22 by adding single-part email detection (HTML)
  grammars/language-eml.cson
  spec/fixtures/single-part.eml
Labels: :heart: Community, Feature
